language: python
python:
  - "3.6"
notifications:
    email: false
# command to install dependencies
install:
  - sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 build-essential swig
  - pip install pycodestyle
  - pip install flake8
  - pip install autopep8
  - pip install -r requirements.txt
# command to run tests
script:
  - cd "$TRAVIS_BUILD_DIR"
  - find . -name \*.py -exec flake8 --statistics {} \;
